name: Project Activity
author: Andy
description: Generates an email summary of project activity for a repo.  The summary shows which cards have moved, been added or with new comments.
inputs:
    token:
        description: "Github Token"
        required: true
    smtp-server:
        description: "SMTP server"
        required: true
    smtp-server-port:
        description: "SMTP server port"
        required: true
    auth-user:
        description: "Sender user email"
        required: true
    auth-pwd:
        description: "Sender user password (for gmail generate and use an app password)"
        required: true
    email-from:
        description: "Sender from name"
        required: true
    recipient-emails:
        description: "Recipents email addresses (comma-separated)"
        required: true
    project-numbers:
        description: "Project Numbers (comma-separated list, or, all)"
        required: required
    days:
        description: "Days back, from run date, of project activity to summarise"
        required: true
runs:
    using: "node12"
    main: "dist/index.js"
branding:
    icon: 'activity'
    color: 'blue'
