name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          smtp-server: "smtp.gmail.com"
          smtp-server-port: "587"
          auth-user: ""
          auth-pwd: ""
          email-from: ""
          recipient-emails: ""
          project-numbers: all
          phase-calendar-days: 7